version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1
  node: circleci/node@4.1.0

commands:
  appraisal-install:
    parameters:
      appraisal:
        type: string
    steps:
      - run:
          name: Copy lockfile
          command: |
            bundle exec appraisal << parameters.appraisal >>  "cp \$BUNDLE_GEMFILE.lock current_appraisal.gemfile.lock"
      - restore_cache:
          name: Restore Appraisal package cache
          keys:
            - v2-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "current_appraisal.gemfile.lock" }}
            - v2-gem-cache-{{ arch }}-{{ .Branch }}-
            - v2-gem-cache-{{ arch }}-
      - run:
          name: Install appraisal dependencies
          command: |
            bundle exec appraisal << parameters.appraisal >> bundle install --jobs=4 --retry=3 --path=../vendor/bundle
      - save_cache:
          name: Save Appraisal package cache
          key: v2-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "current_appraisal.gemfile.lock" }}
          paths:
            - ./vendor/bundle

jobs:
  ruby-test:
    parameters:
      appraisal:
        type: string
    docker:
      - image: cimg/ruby:2.6-node
    environment:
      BUNDLE_APP_CONFIG: .bundle
    steps:
      - checkout
      - ruby/install-deps
      - appraisal-install:
          appraisal: << parameters.appraisal >>
      - run: bundle config list
      - run: bundle exec appraisal << parameters.appraisal >> bundle config list
      - run: bundle exec appraisal << parameters.appraisal >> rake
  lint:
    docker:
      - image: 'cimg/ruby:2.6-node'
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  yarn-install:

  release:
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run: npx semantic-release

workflows:
  version: 2
  main:
    jobs:
      - lint
      - ruby-test:
          matrix:
            parameters:
              appraisal: ['graphql-1.9', 'graphql-1.10', 'graphql-1.11']
      - release:
          requires:
            - lint
            - ruby-test
